requires 'perl', '5.006';
requires 'CGI::Simple';
requires 'Crypt::URandom';
requires 'Devel::Confess';
requires 'Digest::MD5';
requires 'Env::Path';
requires 'Future::XS';
requires 'Hash::MultiValue';
requires 'HTML::Tagset';
requires 'HTML::Tiny';
requires 'HTML::TreeBuilder';
requires 'HTTP::AcceptLanguage';
requires 'HTTP::Negotiate';
requires 'HTTP::Status';
requires 'IO::String';
requires 'JSON';
requires 'PAGI::Server', '0.002006';
requires 'PAGI::Tools', '0.002002';
requires 'Plack::Middleware::ForceEnv';
requires 'Plack';
requires 'Router::Simple';
requires 'Starman';
requires 'Storable';
requires 'Text::Template';
requires 'Tie::IxHash';
requires 'Time::HiRes';

on configure => sub {
    requires 'ExtUtils::MakeMaker';
};

on build => sub {
    requires 'Capture::Tiny';
    requires 'Test::Deep';
    requires 'Test::Differences';
    requires 'Test::Exception';
    requires 'Test::More';
    requires 'Test::Pod';
    requires 'Test::Simple', '0.44';
};
