#  
# WebDyne docker image for Fedora
#
# ====
#
# Override with --build-arg
#
ARG BASE=debian:bookworm
ARG PORT=8080
ARG WORKERS=8


# Default paths
#
ARG PERL_CARTON_PATH="/opt/webdyne"
ARG DOCUMENT_ROOT="/app"


# ====
#
# Build stages
#


# Using Fedora as base
#
FROM ${BASE}


# Redeclare ARGS
#
ARG PERL_CARTON_PATH


# Install build tools and core Perl modules
#

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libssl-dev \
    libperl-dev \
    curl \
    perl \
    cpanminus \
    git \
    && rm -rf /var/lib/apt/lists/*


# Set up app
#
WORKDIR /app

#  Install Carton
#
RUN pwd
RUN which curl
RUN ls -l
#RUN cpanm --notest Carton
#RUN cpanm LWP::UserAgent
RUN /usr/bin/curl -L -o carton.tgz https://github.com/perl-carton/carton/archive/refs/tags/v1.0.35.tar.gz 
RUN ls -l
RUN tar -xvzf carton.tgz
RUN ls -l carton-1.0.35
RUN cd carton-1.0.35 && perl Makefile.PL && make install
#RUN cpanm ./carton.tgz || (echo "Carton install failed. Dumping build.log:" && cat /root/.cpanm/work/*/build.log && exit 1)
#RUN cpanm --notest Carton || (echo "Carton install failed. Dumping build.log:" && cat /root/.cpanm/work/*/build.log && exit 1)
#RUN cpanm --notest https://github.com/perl-carton/carton/archive/refs/tags/v1.0.35.tar.gz || (echo "Carton install failed. Dumping build.log:" && cat /root/.cpanm/work/*/build.log && exit 1)


CMD []

