site_name: WebDyne
site_url: https://aspeer.github.io/WebDyne/
site_author: Andrew Speer
site_description: Engine for creation of dynamic HTML pages with embedded Perl
docs_dir: docs
site_dir: site

repo_name: aspeer/WebDyne
repo_url: https://github.com/aspeer/WebDyne

copyright: Copyright &copy; 2025 Andrew Speer

theme:
  name: material
  features:
    - announce.dismiss
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  icon:
    logo: logo

extra_css:
  - assets/stylesheets/webdyne-mkdocs.css

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-simple-hooks:
      hooks:
        on_page_markdown: "doc.mkdocs.hooks.local_deploy:rewrite_md"
  - redirects:
      redirect_maps:
        index.md: 00_introduction.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aspeer/WebDyne
      name: WebDyne on GitHub
    - icon: fontawesome/solid/code
      link: https://www.perl.org
      name: Perl
    - icon: fontawesome/brands/docker
      link: https://github.com/aspeer/WebDyne/pkgs/container/webdyne
      name: WebDyne container images

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: aspeer
      repo: WebDyne
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
